unicef-polymer/etools-modules-common

- .eslintrc.json
- .prettierrc
- package-lock.json
- package.json
- src_ts/utils/validation-helper.ts
[ch26861]Saving focal points on an old active PD will not trigger a request to the BE
> [ch26861]Validation fix / Saving focal points on an old active PD will not trigger a request to the BE

- package.json
- src_ts/components/cancel/reason-display.ts
> [ch27527] Improve reason-display component

- gulpfile.js
- package-lock.json
- package.json
- src_ts/components/info-icon-tooltip.ts
> Use migrated components- part2 

- package-lock.json
- package.json
- src_ts/components/info-icon-tooltip.ts
- src_ts/styles/info-element-styles.ts
> [ch27186] Tooltips issues

- gulpfile.js
- package-lock.json
- package.json
> [ch27901]Fix environment dependent bug in the gulp build

- package-lock.json
- package.json
[ch27993] Intermittent RangeError: Maximum call stack size exceeded
> [ch27993] Intermittent RangeError: Maximum call stack size exceeded

- package-lock.json
- package.json
- src_ts/mixins/component-base-mixin.ts
- src_ts/mixins/definition_files/component-base-mixin.d.ts
- src_ts/mixins/definition_files/model-changed-mixin.d.ts
- src_ts/mixins/model-changed-mixin.ts
[ch30429] [Editor] Refactor - extract reusable methods, templates
> [ch30429] [Editor] Refactor - extract reusable methods, templates

- package-lock.json
- package.json
- src_ts/mixins/model-changed-mixin.ts
> [ch31858]Fix validation not triggered on change from empty field to 0

- package-lock.json
- package.json
- src_ts/layout/export-data.ts
- src_ts/layout/status/etools-status.ts
- src_ts/utils/date-utils.ts
- src_ts/utils/utils.ts
[ch31393] Missing Russian translations part II (Partners)
> [ch31393] Missing Russian translations part II (Partners)

- package-lock.json
- package.json
- src_ts/styles/shared-styles-lit.ts
[ch31952] The Search section of the dropdown is covered by the header
> [ch31952] The Search section of the dropdown is covered by the header(z-index)

- package-lock.json
- package.json
- src_ts/list/list-helper.ts
[ch32237] PD list: adjust No results to display
> [ch32237] PD list: adjust No results to display

- package-lock.json
- package.json
- src_ts/styles/shared-styles-lit.ts
[ch32780] Tab navigation: Unwanted black border on focus
> [ch32780] Tab navigation: Unwanted black border on focus

- package-lock.json
- package.json
> Update utils package

- package-lock.json
- package.json
- src_ts/available-actions/available-actions.ts
- src_ts/components/cancel/cancel-justification.ts
- src_ts/components/cancel/reason-display.ts
- src_ts/mixins/content-panel-mixin.ts
- src_ts/mixins/definition_files/content-panel-mixin.d.ts
- src_ts/mixins/definition_files/fr-numbers-consistency-mixin.d.ts
- src_ts/mixins/fr-numbers-consistency-mixin.ts
- src_ts/utils/types.ts
> Fix typing mixin + rc.3

- package-lock.json
- package.json
- src_ts/styles/shared-styles-lit.ts
> [ch34761]Remove CSS mixins

- src_ts/styles/button-styles.ts
> [ch34901]Update link button font

- package-lock.json
- package.json
- src_ts/mixins/component-base-mixin.ts
- src_ts/styles/action-icon-btns-styles.ts
- src_ts/styles/button-styles.ts
- src_ts/styles/shared-styles-lit.ts
> [ch35000]Tweaks for sl-icon-button

- src_ts/components/cancel/cancel-justification.ts
- src_ts/components/cancel/reason-display.ts
- src_ts/layout/etools-tabs.ts
- src_ts/layout/icons-actions.ts
- src_ts/layout/status/etools-status.ts
- src_ts/mixins/component-base-mixin.ts
- src_ts/styles/button-styles.ts
- src_ts/styles/fr-warnings-styles.ts
- src_ts/styles/shared-styles-lit.ts
replace icons on sl-icon-button, sl-icon + more icon changes & style fixes
[ch35018] Replace icons back with the old ones
> [ch35018] Replace icons back with the old ones

- package-lock.json
- package.json
- src_ts/mixins/fr-numbers-consistency-mixin.ts
Adding version rc.11 + icons fix
> Adding version rc.11 + icons fix

- package-lock.json
- package.json
> Version update 5.0.0-rc.14

- package-lock.json
- package.json
- src_ts/styles/button-styles.ts
Fixes button styles version rc15
> Fixes button styles

- package-lock.json
- package.json
- src_ts/layout/page-content-header/page-content-header.ts
- src_ts/list/list-helper.ts
- src_ts/mixins/data-mixin.ts
- src_ts/mixins/endpoints-mixin-lit.ts
- src_ts/mixins/environment-flags-mixin.ts
- src_ts/mixins/repeatable-data-sets-mixin.ts
- src_ts/mixins/uploads-mixin.ts
- src_ts/styles/content-section-styles-lit.ts
- src_ts/styles/content-section-styles-polymer.ts
- src_ts/styles/label-and-value-styles-lit.ts
- src_ts/styles/required-fields-styles.ts
- src_ts/utils/request-helper.ts
- src_ts/utils/validation-helper.ts
Remove paper leftovers, remove @apply
> Cleanup and fixes

- package-lock.json
- package.json
- src_ts/styles/readonly-styles.ts
- src_ts/styles/shared-styles-lit.ts
> Cleanup paper styles

- package-lock.json
- package.json
- tsconfig.json
> rc.19, import helpers tsc

- package-lock.json
- package.json
- src_ts/mixins/component-base-mixin.ts
- src_ts/styles/shared-styles-lit.ts
[ch35301] PMP & ePD shoelace migration issues 3
> [ch35301] PMP & ePD shoelace migration issues 3

- src_ts/styles/button-styles.ts
[ch35333] Clean-up, refactor, fix buttons
> [ch35333] Clean-up, refactor, fix buttons

- src_ts/layout/are-you-sure.ts
- src_ts/styles/shared-styles-lit.ts
[ch35358] Fix dialog delete button
> [ch35358] Fix dialog delete button

- src_ts/layout/etools-tabs.ts
[ch35394] etools tabs fixes for indicator dialog
> [ch35394] etools tabs fixes for indicator dialog

- package-lock.json
- package.json
[ch35560] PMP & ePD shoelace migration issues 7
> [ch35560] PMP & ePD shoelace migration issues 7

- package-lock.json
- package.json
- src_ts/layout/etools-tabs.ts
[ch35727] FM Shoelace Migration Issues
> [ch35727] FM Shoelace Migration Issues

- package-lock.json
- package.json
- src_ts/layout/etools-tabs.ts
[ch35759] [ch35830] Fm migrations 2&3
> [ch35759] [ch35830] Fm migrations 2&3

- package-lock.json
- package.json
- src_ts/layout/etools-tabs.ts
> Fix tabs + rc.32

- package-lock.json
- package.json
- src_ts/layout/are-you-sure.ts
Improve are-you-sure dialog, display text as html
> Improve are-you-sure dialog, display text as html

- package-lock.json
- package.json
- src_ts/layout/etools-tabs.ts
[ch36030] FM Shoelace Migration 4
Published rc.34
> [ch36030] FM Shoelace Migration 4

- package-lock.json
- src_ts/layout/are-you-sure.ts
- src_ts/styles/shared-styles-lit.ts
[ch36250] Cannot delete data from multiple tabs/tabels
> [ch36250] Cannot delete data from multiple tabs/tabels

- package-lock.json
- package.json
- src_ts/components/cancel/cancel-justification.ts
- src_ts/components/cancel/reason-display.ts
- src_ts/layout/page-content-header/page-content-header.ts
- src_ts/layout/status/etools-status.ts
- src_ts/list/list-styles.ts
- src_ts/styles/label-and-value-styles-lit.ts
- src_ts/styles/repeatable-data-sets-styles.ts
- src_ts/styles/shared-styles-lit.ts
[ch36239] Adding etools-accesiblity, rc.60
> [ch36239] Adding etools-accesiblity, rc.60

- package-lock.json
- package.json
- src_ts/layout/status/etools-status.ts
- src_ts/mixins/component-base-mixin.ts
> Mobile friendly fixes

- package-lock.json
- package.json
- src_ts/styles/grid-layout-styles-lit.ts
- src_ts/styles/shared-styles-lit.ts
> Mobile fixes

- package-lock.json
- package.json
- src_ts/layout/etools-tabs.ts
Fix active tab problem when dynamic tabs are used
> Fix active tab problem when dynamic tabs are used

- package-lock.json
- package.json
- src_ts/config/config.ts
- src_ts/mixins/endpoints-mixin-lit.ts
> Add environment from utils

- package-lock.json
- package.json
- src_ts/components/buttons/support-button.ts
- src_ts/components/dropdowns/countries-dropdown.ts
- src_ts/components/dropdowns/languages-dropdown.ts
- src_ts/components/dropdowns/organizations-dropdown.ts
- src_ts/utils/language.ts
> 37311 move components
